connected traces/ports highlight v2
tscircuit/pcb-viewer pull request #49
Opened 2024-09-06 20:27 UTC by ShiboSoftwareDev

![image](https://github.com/user-attachments/assets/e177965f-d712-4c58-941c-abeb9bb89f86)
@seveibar can you check this warning out? I think it's because global state is being changed from two places at the same time but I'm not sure

2024-09-06 20:30 UTC, seveibar commented on src/components/CanvasElementsRenderer.tsx
> +  const getGlobalId = useGlobalStore((state) => state.getGlobalId)
Instead of putting this on the global store, just define it as a mutating global method:

```
let globalIdCounter = 0
function getGlobalId() {
  return `globalid_${globalIdCounter++}`
}
```

2024-09-06 20:30 UTC, seveibar commented on src/components/CanvasElementsRenderer.tsx
> +  const getGlobalId = useGlobalStore((state) => state.getGlobalId)
this may fix the console issue

2024-09-06 20:31 UTC, seveibar commented on src/components/CanvasElementsRenderer.tsx
> +  const highlightedConnectedPrimitives = useMemo(() => {
```suggestion
  const primitivesWithHighlights = useMemo(() => {
```

2024-09-06 20:31 UTC, seveibar commented on src/components/CanvasElementsRenderer.tsx
> +      return convertElementToPrimitives(elm, props.elements, getGlobalId)
```suggestion
      return convertElementToPrimitives(elm, props.elements)
```

2024-09-06 20:35 UTC, seveibar commented on src/components/MouseElementTracker.tsx
> +    return newHighlightedPrimitives
you should undo most of the changes in this file and just change line 115 so that it's 

```ts
setMousedPrimitives(mousedPrimitives)
setHighlightedPrimitives(mousedPrimitives.map(p => p._drawing_object_id)
```

2024-09-06 20:38 UTC, ShiboSoftwareDev commented on src/components/MouseElementTracker.tsx
> +    return newHighlightedPrimitives
I did the check so that highlightedPrimitives don't change on every mouse movement, it updated so frequently. Is that okay?

2024-09-06 20:40 UTC, seveibar commented on src/lib/getElectricallyConnectedPrimitiveIds.ts
> +export const getElectricallyConnectedPrimitiveIds = (
Not a huge fan of this function definition, very hard to follow.

```ts
isElementElectricallyConnected(elm: AnySoupElement, allElements: AnySoupElement[])
```

that signature makes a lot of sense and can be used to determine if an element is highlighted

```ts
if (isElementElectricallyConnected(primitive._element, soup)) {
  primitive.highlighted = true
}
```

2024-09-06 20:41 UTC, seveibar commented on src/lib/Drawer.ts
> +    }
nice

2024-09-06 20:47 UTC, seveibar commented on src/components/MouseElementTracker.tsx
> +    return newHighlightedPrimitives
yea that's fine, it also applied to moused primitives. Let's give it a better name though

Probably something like this, also have to add support for the connected primitives


```tsx

if (hasSamePrimitives(oldMousedPrimitives, newMousedPrimitives)) return

setMousedPrimitives(mousedPrimitives)
setHighlightedPrimitives(
  mousedPrimitives.flatMap(mousedPrimitive => getAllConnectedPrimitives({
    mousedPrimitive,
    allPrimitives: primitives,
  }))
)
```

2024-09-06 20:49 UTC, seveibar requested changes
looking a lot better. We can also break this PR into two parts:

1. Highlighting only moused primitives
2. Highlighting any primitive connected to a moused primitive

When I worked on universal data tool, i let a lot of PRs in that IMO didn't have super clear code and it eventually made the project really difficult to contribute to, so that's why i'm being a bit more difficult on this PR, because I know the consequences of a UI project if it starts to get really complicated. Would definitely recommend breaking into two parts!!!

2024-09-06 21:05 UTC, ShiboSoftwareDev commented
@seveibar I'll do my best

2024-09-08 22:36 UTC, seveibar commented
Looking pretty good!!

2024-09-08 22:37 UTC, seveibar commented
One issue is we shouldnt have a big object inside the global store if we can avoid it, this is why i suggest primitive ids as a list

2024-09-08 22:39 UTC, seveibar commented
I'm going to try to do a quick video review again as soon as i get home from a conference!

2024-09-09 04:20 UTC, closed without merging