Added hotkeys for all layers
tscircuit/pcb-viewer pull request #61
Opened 2024-09-18 13:37 UTC by anas-sarkez

2024-09-18 15:10 UTC, imrishabh18 commented
@anas-sarkez Can you remove the `package-lock.json` from the PR? Otherwise, looks good

2024-09-18 16:01 UTC, seveibar requested changes
This is pretty good but i think if we introduce a useHotkey hook we'd have an easier time making more and more hotkeys

2024-09-18 16:01 UTC, seveibar commented on src/components/ToolbarOverlay.tsx
> +    const handleKeyDown = (event: KeyboardEvent) => {
I think we have to do a check to make sure that the mouse is over the pcb viewer otherwise if there are multiple pcb viewers this vhsnges all of them.

I _think_ we might have other hotkeys that use this technique, i think we should have a useHotkey("ctrl+1", () => ...) hook that manages the whole thing

2024-09-18 17:50 UTC, imrishabh18 commented on src/components/ToolbarOverlay.tsx
> +    const handleKeyDown = (event: KeyboardEvent) => {
Yeah, this makes sense

2024-09-19 17:23 UTC, seveibar commented on src/components/ToolbarOverlay.tsx
> +  useHotKey([
can we simplify the signature of this method to...

```tsx
useHotkey("1", () => selectLayer("top"))
```

2024-09-19 17:23 UTC, anas-sarkez commented
@seveibar check the last commit

2024-09-19 17:25 UTC, seveibar commented on src/components/ToolbarOverlay.tsx
> +  useHotKey([
it's ok that it's called multiple times.

if we merge this we'll also want to create an issue that makes sure that the window is focused to activate a hotkey

2024-09-19 17:27 UTC, seveibar commented
we're getting closer!!! I appreciate all the work 🙏

2024-09-19 17:27 UTC, seveibar commented on src/hooks/useHotKey.ts
> +                const mainKey = keyParts[keyParts.length - 1];
i like this, pretty simple

2024-09-20 15:33 UTC, seveibar requested changes
See unresolved comment! 🙏

2024-09-22 04:44 UTC, anas-sarkez commented
@seveibar 
check last commit

2024-09-22 16:03 UTC, seveibar approved these changes

2024-09-28 05:41 UTC, merged